# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{modulesPath, ...}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd" "btintel"];
  boot.extraModulePackages = [];
  boot.resumeDevice = "/dev/disk/by-uuid/2a9f30ad-dc12-45af-8351-4700123e1700";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7edc6fe9-2aab-429a-baa4-2187bbf3186f";
    fsType = "f2fs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FE10-AE4C";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/f825b422-d860-4579-90cf-dc0af7651f62";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "autodefrag"
    ];
  };

  fileSystems."/run/media/Media" = {
    device = "/dev/disk/by-uuid/5b5ff03b-1335-4810-a047-4e482283ea94";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "autodefrag"
    ];
  };

  swapDevices = [{device = "/dev/disk/by-uuid/2a9f30ad-dc12-45af-8351-4700123e1700";}];
}
