#!/bin/sh
>&2 echo "[STEAMOS] $0: stub called with: $*"
# Exit codes according to vendor:
# 0 - update success/update available
# 7 - no update available
# -1 - update error
# -22 - unknown option
exit 7
